import '../../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AsideLeft from '@/components/Aside-left/AsideLeft';
import { Toaster } from 'react-hot-toast';
import { DictionaryProvider } from '../context/DictionaryContext';
import { Locale } from '@/config/i18n.config';
import ButtonTop from '@/components/btn-top/ButtonTop';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'sdas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: Locale } }) {
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} flex bg-[#17161a]`}>
        <Toaster   position="bottom-center"
  reverseOrder={false}
  />
  <ButtonTop />
  <DictionaryProvider lang={params.lang}>
        <AsideLeft />
        {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
