import '../../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Nav } from '@/components/Nav/Nav';
import AsideLeft from '@/components/Aside-left/AsideLeft';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'sdas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} flex`}>
        <AsideLeft />
        {children}
      </body>
    </html>
  );
}
